### ISSUE TITLE
Build Failed : error: unused import: `str` : 0.3.2 Release

### ISSUE THREAD

**Issue by sinkarharshad** [redox-os/redox#1060]
Reproduction: `make all`

Expected behavior: Build should work fine

Actual behavior: Build is getting failed due to "error: unused import: `str`"

Build information: 
```
cook - redoxfs fetch
Cloning into 'source'...
remote: Counting objects: 827, done.
remote: Total 827 (delta 0), reused 0 (delta 0), pack-reused 827
Receiving objects: 100% (827/827), 164.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (529/529), done.
Checking connectivity... done.
Already up-to-date.
repo - preparing redoxfs
cook - redoxfs prepare
repo - building redoxfs
cook - redoxfs build
   Compiling redox_syscall v0.1.30
   Compiling spin v0.4.5
   Compiling redoxfs v0.1.2 (file:///home/shk4abt/devel/REDOX0.3.2/redox/cookbook/recipes/redoxfs/build)
error: unused import: `str`
 --> mkfs/main.rs:6:25
  |
6 | use std::{env, process, str, time};
  |                         ^^^
  |
note: lint level defined here
 --> mkfs/main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: #[deny(unused_imports)] implied by #[deny(warnings)]

error: aborting due to previous error

error: Could not compile `redoxfs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
./repo.sh failed.mk/initfs.mk:2: recipe for target 'build/initfs.tag' failed
make: *** [build/initfs.tag] Error 1
```
Thank you in advance!

**Comment by ids1024** [comment]
This should be resolved once https://github.com/redox-os/redoxfs/pull/34 and https://github.com/redox-os/orbital/pull/17 are merged.

**Comment by sinkarharshad** [comment]
@jackpot51 @ids1024 i tried again, but the error is still there :!
