### ISSUE TITLE
Not able to open redox-terminal (ion)

### ISSUE THREAD

**Issue by sinkarharshad** [redox-os/redox#1063]
Host Machine: Ubuntu 16.04

Reproduction: `make qemu`

Expected behavior: Redox-Terminal (ion) should work

Actual behavior: Terminal is not accessible. Whenever I click, getting following lines :

```
redox login: Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(47)
NAME file:/bin/ion
Kill 47 9
Send 9 to 47
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(49)
NAME file:/bin/ion
Kill 49 9
Send 9 to 49
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF400021A240
  FFFFFF400021A240: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF400021A2C0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(51)
NAME file:/bin/ion
Kill 51 9
Send 9 to 51
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(53)
NAME file:/bin/ion
Kill 53 9
Send 9 to 53
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(55)
NAME file:/bin/ion
Kill 55 9
Send 9 to 55
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(57)
NAME file:/bin/ion
Kill 57 9
Send 9 to 57
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF4000208E40
  FFFFFF4000208E40: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF4000208EC0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(59)
NAME file:/bin/ion
Kill 59 9
Send 9 to 59
Found 1, sent to 1
Protection fault: 0 at 23:000000000051EE42
TRACE: FFFFFF400021A240
  FFFFFF400021A240: FFFFFF00001903C5
    FFFFFF0000190320+00A5
  FFFFFF400021A2C0: FFFFFF0000190311
  00000180000FFDD0: 00000000004B2F00
  00000180000FFE80: 00000000004002C5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(61)
NAME file:/bin/ion
Kill 61 9
Send 9 to 61
Found 1, sent to 1
```
I have clicked several times on terminal icon to generate this. 
Kindly help me to resolve this one.
Thank you in advance.

**Comment by jackpot51** [comment]
If you have built the system locally, please do not identify a release number in the bug. The actual 0.3.2 release ISO does not have this behavior, so the bug occurred some time after release.

**Comment by jackpot51** [comment]
It may have been caused by https://github.com/redox-os/ion/pull/527

**Comment by sinkarharshad** [comment]
@jackpot51 How to overcome this? or any way to go back to the previous build?

**Comment by sinkarharshad** [comment]
It did work with: `make qemu kvm=no` 
@jackpot51 Should I close the issue?

**Comment by jackpot51** [comment]
No, no, no. There is clearly an issue, I believe with SSE alignment

**Comment by jackpot51** [comment]
Fixed in https://github.com/redox-os/kernel/commit/917d30c193edd6a7c4bdbf89f78c59299f4b4f4d

**Comment by zen3ger** [comment]
@jackpot51 with [redox-os/kernel@a9fa08f](https://github.com/redox-os/kernel/commit/a9fa08fd7221db9615a482b8a8396829f7c4fc2f) the problem is back. Is there anything I should look into?

```
redox login: Page fault: 0000000000000000
RFLAG: 0000000000010246
CS:    0000000000000023
RIP:   000000000056E16F
CODE:  0000000000000006
RAX:   0000028000001000
RCX:   0000028000001000
RDX:   0000000000000A30
RDI:   00000080000005C0
RSI:   00000080000005F0
R8:    8080808080808080
R9:    0000000200000000
R10:   0000000000000000
R11:   0000000000000065
RBX:   0000000000000000
RBP:   00000180000FFC40
R12:   0000000000000019
R13:   000000000000002E
R14:   00000080000005C0
R15:   00000000005F6718
FS:    0000000000000033
TRACE: FFFFFF40001D3D50
  FFFFFF40001D3D50: FFFFFF000019D6C5
    FFFFFF000019D620+00A5
    kernel::arch::x86_64::interrupt::exception::page::inner::h0f73f5d3fb18f21f
  FFFFFF40001D3DB0: FFFFFF000019D61B
    FFFFFF000019D5F0+002B
    kernel::arch::x86_64::interrupt::exception::page::hc0ca9eb815299673
  00000180000FFC40: 0000000000575E86
  00000180000FFD30: 0000000000575AE2
  00000180000FFD70: 000000000056E30C
  00000180000FFDC0: 00000000005763F9
  00000180000FFE80: 00000000004001F5
 0000008000000018: EMPTY RETURN
SIGNAL 11, CPU 0, PID ContextId(38)
NAME file:/bin/ion
Kill 38 9
Send 9 to 38
Found 1, sent to 1
```

**Comment by jackpot51** [comment]
This looks like a different issue. What processor are you running on? Does using `make qemu kvm=no` fix the issue?

**Comment by zen3ger** [comment]
Intel Core i5-3570. `make qemu kvm=no` doesn't fix it, btw kvm is enabled.

**Comment by sajattack** [comment]
It's a known issue with ion, you can use bash for now by editing /etc/passwd.

**Comment by garethellis0** [comment]
Dumb question, but how should `/etc/passwd` be edited to use `bash`? I would expect changing `/bin/ion` to `/bin/bash`, but `/bin/bash` doesn't seem to exist for me? Again, sorry for the dumb question, just getting started with redox.

**Comment by sajattack** [comment]
Uncomment bash in filesystem.toml and run make.

**Comment by sinkarharshad** [comment]
@sajattack  : Uncomment bash in filesystem.toml and run make : This did not work for me.

**Comment by sajattack** [comment]
Did you also edit /etc/passwd?

**Comment by sinkarharshad** [comment]
@sajattack "/etc/passwd": Where? 
```
$ find . -name "passwd"
./cookbook/recipes/userutils/stage/ref/passwd -- (this one?, if yes: what to edit? )
./cookbook/recipes/userutils/stage/bin/passwd
./cookbook/recipes/userutils/build/target/x86_64-unknown-redox/release/passwd
```

**Comment by sajattack** [comment]
https://github.com/redox-os/redox/issues/1124#issuecomment-353178341
