### ISSUE TITLE
Latest Redox build does not compile

### ISSUE THREAD

**Issue by k0pernicus** [redox-os/redox#503]
Hi there!

I try to compile the latest Redox-os build, but it seems it doesn't compile, due to an internal compiler error.
This is the compilation error:

```
RUST_BACKTRACE=1 rustc --target=i386-unknown-redox.json -L build/i386-unknown-redox/debug -C no-prepopulate-passes -C no-stack-check -C opt-level=2 -Z no-landing-pads -A dead_code -o build/i386-unknown-redox/debug/liballoc.rlib rust/src/liballoc/lib.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'box_free language item is missing', ../src/libcore/option.rs:704
stack backtrace:
   1:     0x2ad81af1a7e0 - sys::backtrace::tracing::imp::write::h558d5f2978e55ac4ttu
   2:     0x2ad81af2237b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43200
   3:     0x2ad81af21ed3 - panicking::default_handler::hbf3975cab47e4b81VWy
   4:     0x2ad81aeebd8c - sys_common::unwind::begin_unwind_inner::h78f1521fe1f5d27biit
   5:     0x2ad81aeec828 - sys_common::unwind::begin_unwind_fmt::h964018da5137d3feoht
   6:     0x2ad81af182e1 - rust_begin_unwind
   7:     0x2ad81af68d7f - panicking::panic_fmt::h1951bd5aee0da5596YL
   8:     0x2ad81af88884 - option::expect_failed::h9cc346d7ce275f32ftO
   9:     0x2ad81cef907a - build::scope::Builder<'a, 'tcx>::diverge_cleanup::heb2dc5d5536e3632Gad
  10:     0x2ad81ced7e70 - build::scope::Builder<'a, 'tcx>::pop_scope::hca717148f2269680e0c
  11:     0x2ad81cef31d4 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb0ea7a8fb62013457a
  12:     0x2ad81ceed3dc - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::_$u7b$$u7b$closure$u7d$$u7d$::closure.19083
  13:     0x2ad81cee489b - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::h597b8b19dddfaf21oCa
  14:     0x2ad81cef29e3 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb0ea7a8fb62013457a
  15:     0x2ad81cedb59e - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::hfbe2e392e51e8eac8pb
  16:     0x2ad81cef31c3 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb0ea7a8fb62013457a
  17:     0x2ad81cedb59e - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::hfbe2e392e51e8eac8pb
  18:     0x2ad81ced8f99 - build::block::Builder<'a, 'tcx>::ast_block::hd2d2edaabe6cb515Cka
  19:     0x2ad81ced4918 - build::construct::ha32a5a60c00e1d44dca
  20:     0x2ad81cf1e7ce - mir_map::InnerDump<'a, 'm, 'tcx>.Visitor<'tcx>::visit_fn::h28cf6740ed874f78oqg
  21:     0x2ad81cf260d7 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_impl_item::hd9dd230cd7a2e137Qog
  22:     0x2ad81cf1cc11 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_item::hd3c93606f62b1924zng
  23:     0x2ad81cf1bc5b - mir_map::build_mir_for_crate::h119d9e46f857102eJlg
  24:     0x2ad81ab2622f - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.27916
  25:     0x2ad81ab2211e - middle::ty::context::ctxt<'tcx>::create_and_enter::h7708584257925507687
  26:     0x2ad81ab1e273 - driver::phase_3_run_analysis_passes::h14974517076103833877
  27:     0x2ad81aaf1078 - driver::compile_input::h3e569cf7fd226ecaBca
  28:     0x2ad81aae13e9 - run_compiler::h38b6440e1875c9dbQGc
  29:     0x2ad81aade931 - sys_common::unwind::try::try_fn::h12203405518419617659
  30:     0x2ad81af1826b - __rust_try
  31:     0x2ad81af107ad - sys_common::unwind::inner_try::h876b2793e1ec4011kft
  32:     0x2ad81aadf180 - boxed::F.FnBox<A>::call_box::h3648721114673177547
  33:     0x2ad81af20940 - sys::thread::Thread::new::thread_start::h36aef2efeb591414fUx
  34:     0x2ad822914181 - start_thread
  35:     0x2ad81b4c747c - __clone
  36:                0x0 - <unknown>

make: *** [build/i386-unknown-redox/debug/liballoc.rlib] Erreur 101
```

I run Redox-OS with the latest nightly of Rust:

```
rustc --version
--> rustc 1.8.0-nightly (75271d8f1 2016-02-09)
``` 

Any idea here please? :-/

**Comment by Ticki** [comment]
Should be fixed by https://github.com/redox-os/rust/pull/6.

**Comment by tormeh** [comment]
Doesn't look like it is... I got basically the same error just now:

`error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'box_free language item is missing', ../src/libcore/option.rs:704
stack backtrace:
   1:     0x7f1c89580800 - sys::backtrace::tracing::imp::write::h558d5f2978e55ac4ttu
   2:     0x7f1c8958839b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43238
   3:     0x7f1c89587ef3 - panicking::default_handler::hbf3975cab47e4b81VWy
   4:     0x7f1c89551dac - sys_common::unwind::begin_unwind_inner::h78f1521fe1f5d27biit
   5:     0x7f1c89552848 - sys_common::unwind::begin_unwind_fmt::h964018da5137d3feoht
   6:     0x7f1c8957e301 - rust_begin_unwind
   7:     0x7f1c895ced9f - panicking::panic_fmt::h7eb7bd8738a5380b6YL
   8:     0x7f1c895ee8a4 - option::expect_failed::h87adce2046c3981eftO
   9:     0x7f1c8771efba - build::scope::Builder<'a, 'tcx>::diverge_cleanup::h3921300aec2fd7f1Gad
  10:     0x7f1c876fddb0 - build::scope::Builder<'a, 'tcx>::pop_scope::h0625f1997c9b671ae0c
  11:     0x7f1c87719114 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
  12:     0x7f1c8771331c - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::_$u7b$$u7b$closure$u7d$$u7d$::closure.19098
  13:     0x7f1c8770a7db - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::h0ab94e6328799876oCa
  14:     0x7f1c87718923 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
  15:     0x7f1c877014de - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::h8d4f8b6bb51503d78pb
  16:     0x7f1c87719103 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
  17:     0x7f1c877014de - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::h8d4f8b6bb51503d78pb
  18:     0x7f1c876feed9 - build::block::Builder<'a, 'tcx>::ast_block::he45b75545bd4b7c3Cka
  19:     0x7f1c876fa858 - build::construct::he10071c6f2b0cbfedca
  20:     0x7f1c8774470e - mir_map::InnerDump<'a, 'm, 'tcx>.Visitor<'tcx>::visit_fn::hd88910231bcdb938iqg
  21:     0x7f1c8774c017 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_impl_item::h856797710c67276bKog
  22:     0x7f1c87742b51 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_item::h86492f3725319a14tng
  23:     0x7f1c87741b9b - mir_map::build_mir_for_crate::h28ba6c860f5d5b74Clg
  24:     0x7f1c89aa031f - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.27964
  25:     0x7f1c89a9c20e - middle::ty::context::ctxt<'tcx>::create_and_enter::h5439679730299442922
  26:     0x7f1c89a98363 - driver::phase_3_run_analysis_passes::h12589397492560770879
  27:     0x7f1c89a6b0d8 - driver::compile_input::hb24a9d779e578b83Bca
  28:     0x7f1c89a5b3e8 - run_compiler::hf1f6ba491f28518acHc
  29:     0x7f1c89a588d1 - sys_common::unwind::try::try_fn::h10141810680521866859
  30:     0x7f1c8957e28b - __rust_try
  31:     0x7f1c895767cd - sys_common::unwind::inner_try::h876b2793e1ec4011kft
  32:     0x7f1c89a59120 - boxed::F.FnBox<A>::call_box::h14464204619411869790
  33:     0x7f1c89586960 - sys::thread::Thread::new::thread_start::h36aef2efeb591414fUx
  34:     0x7f1c81d196a9 - start_thread
  35:     0x7f1c891f8eec - clone
  36:                0x0 - <unknown>

Makefile:256: recipe for target 'build/i386-unknown-redox/debug/liballoc.rlib' failed
make: *** [build/i386-unknown-redox/debug/liballoc.rlib] Error 101
`

**Comment by k0pernicus** [comment]
It's true, I updated from upstream, and I still have this error... :-/

**Comment by k0pernicus** [comment]
Ok, it seems that the bug is already known, due to the non-implementation of 'lang' with Redox...
[Issue #31480](https://github.com/rust-lang/rust/issues/31480)

**Comment by k0pernicus** [comment]
Ok, that's seems good now!

```
make clean
git pull upstream master
git submodule update --init
make all
```

Problem solved! :-)
