### ISSUE TITLE
PANIC when running redox on qemu with vga=no

### ISSUE THREAD

**Issue by little-dude** [redox-os/redox#823]
**Reproduction**:

Run `make qemu vga=no`

**Expected behavior**: 

Redox boots up and display the login prompt

**Actual behavior**:

Redox panics before displaying the login prompt:

```
Protection fault: 7FB at 08:FFFFFF000014BAB2
TRACE: FFFFFF0008463D20
  FFFFFF0008463D20: FFFFFF000014EED2
  FFFFFF0008463DA0: FFFFFF000014D551
 FFFFFF0008463EF8: EMPTY RETURN
BSP: Ok(ContextId(1)) 4
SIGNAL 11, CPU 0, PID ContextId(0)
PANIC: exit failed to find context: No such process
FILE: rust/src/libcore/result.rs
LINE: 845
TRACE: FFFFFF0008463800
  FFFFFF0008463800: FFFFFF0000152F4A
  FFFFFF0008463970: FFFFFF0000107F1E
  FFFFFF00084639F0: FFFFFF000013EBD2
  FFFFFF0008463C10: FFFFFF0000147A05
  FFFFFF0008463D20: FFFFFF000014EEDC
  FFFFFF0008463DA0: FFFFFF000014D551
 FFFFFF0008463EF8: EMPTY RETURN
HALT
```

**Build information**:

- `rustc -V`: rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)
- `git rev-parse HEAD`: 1127c771ce95b2f3eed9f7c6f2498d49c0cb4321
- `qemu-system-x86_64 --version`: 2.8.0
- `uname -a`: Linux localhost.localdomain 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Misc**:

- Redox boots fine with `make qemu`.
- WIth `make qemu vga=no kvm=no` I'm seeing a different panic:

```
Invalid opcode fault at 23:000000000040C6D4
TRACE: FFFFFF4000033C78
  FFFFFF4000033C78: FFFFFF000014F3F6
  FFFFFF4000033CE8: FFFFFF000014D431
  00000180000FF970: 000000000040C52D
  00000180000FF9D0: 000000000040C516
  00000180000FFA30: 000000000040C3F3
  00000180000FFA60: 000000000040C348
  00000180000FFAD0: 000000000040C2D8
  00000180000FFB30: 000000000040E0AE
  00000180000FFBA0: 0000000000400298
  00000180000FFC20: 0000000000401CB6
  00000180000FFE10: 000000000040C6CC
  00000180000FFE20: 000000000040C609
  00000180000FFE80: 0000000000410CFC
 0000008000000018: EMPTY RETURN
SIGNAL 4, CPU 0, PID ContextId(5)
NAME initfs:/bin/ps2d
Invalid opcode fault at 23:00000000004137A4
TRACE: FFFFFF4000056CB8
  FFFFFF4000056CB8: FFFFFF000014F3F6
  FFFFFF4000056D28: FFFFFF000014D431
  00000180000FDE30: 000000000041224D
  00000180000FDE90: 0000000000412236
  00000180000FDEF0: 0000000000412113
  00000180000FDF20: 0000000000412068
  00000180000FDF90: 000000000040A3F1
  00000180000FE050: 0000000000404216
  00000180000FE110: 00000000004039BC
  00000180000FEC90: 00000000004086C4
  00000180000FF450: 00000000004088B0
  00000180000FFBD0: 0000000000400E8E
  00000180000FFDE0: 000000000041379C
  00000180000FFDF0: 0000000000412329
  00000180000FFE50: 0000000000416C4C
  0000008000000030: 0000000000000021
  0000000000000000: GUARD PAGE
SIGNAL 4, CPU 0, PID ContextId(8)
```

**full log files**

[redox-panic-vga-no-kvm-no.txt](https://github.com/redox-os/redox/files/703092/redox-panic-vga-no-kvm-no.txt)
[redox-panic-vga-no.txt](https://github.com/redox-os/redox/files/703093/redox-panic-vga-no.txt)

**Comment by jackpot51** [comment]
Thanks! Probably need to detect a missing ps/2 port correctly.

**Comment by jackpot51** [comment]
@little-dude the issue has been fixed with this commit, correctly checking errors on switching stdio in `init`:

https://github.com/redox-os/redox/commit/6a5acfd9a1291976b9ca66355124bdd576d9069c

**Comment by little-dude** [comment]
Thanks @jackpot51 ! it now boots with `vga=no` but I'm still seeing traces:


I also works with `vga=no kvm=no` but I'm still seeing a bunch of traces:
```
init: failed to switch stdio to 'display:1': No such device (os error 19)
thread '<unnamed>' panicked at 'ps2d: failed to open display:input: Error { repr: Os { code: 19, message: "No such device" } }', rust/src/libcore/result.rs:845
Invalid opcode fault at 23:000000000040C6D4
TRACE: FFFFFF4000033C78
  FFFFFF4000033C78: FFFFFF000014F526
  FFFFFF4000033CE8: FFFFFF000014D561
  00000180000FF970: 000000000040C52D
  00000180000FF9D0: 000000000040C516
  00000180000FFA30: 000000000040C3F3
  00000180000FFA60: 000000000040C348
  00000180000FFAD0: 000000000040C2D8
  00000180000FFB30: 000000000040E0AE
  00000180000FFBA0: 0000000000400298
  00000180000FFC20: 0000000000401CB6
  00000180000FFE10: 000000000040C6CC
  00000180000FFE20: 000000000040C609
  00000180000FFE80: 0000000000410CFC
 0000008000000018: EMPTY RETURN
[...]
Invalid opcode fault at 23:000000000040BCE4
TRACE: FFFFFF4000117E78
  FFFFFF4000117E78: FFFFFF000014F526
  FFFFFF4000117EE8: FFFFFF000014D561
  00000180000FE930: 000000000040BA2D
  00000180000FE990: 000000000040BA16
  00000180000FE9F0: 000000000040B8F3
  00000180000FEA20: 000000000040B848
  00000180000FEA90: 000000000040B7D8
  00000180000FEAF0: 000000000040CFEE
  00000180000FEB60: 000000000040022C
  00000180000FEBE0: 00000000004010C0
  00000180000FFE00: 000000000040BCDC
  00000180000FFE10: 000000000040BC19
  00000180000FFE70: 000000000040FB7C
  0000008000000020: 0000000000000021
  0000000000000000: GUARD PAGE
SIGNAL 4, CPU 0, PID ContextId(33)
```

Here is the full log file with `make qemu vga=no`: [redox-traces-vga-no.txt](https://github.com/redox-os/redox/files/704993/redox-traces-vga-no.txt)

- rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)
- redox HEAD: 08a05a8afa04a6f41bd97801039fda129b84d3af

**Comment by jackpot51** [comment]
Those are the graphical interfaces panicking on not finding a display. I am working on better conditional checks to prevent them from being launched when not necessary

**Comment by jackpot51** [comment]
These errors no longer cause panics
