### ISSUE TITLE
LiveCD freezes with network adapter active under VirtualBox

### ISSUE THREAD

**Issue by Dragonrun1** [redox-os/redox#868]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Boot liveCD with Intel PRO active in VirtualBox
**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Get desktop login
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
freezes somewhere in network config
**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
VirtualBox 5.1.16 but also with older version. LiveCD 0.1.1
Here's a screen shot
![virtualbox_redox_08_03_2017_16_17_42](https://cloud.githubusercontent.com/assets/1431541/23730385/f5ec9a34-041b-11e7-903e-3f64e4814ca6.png)

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by Dragonrun1** [comment]
Just found issue #821 which was from several versions back is it still not working?

**Comment by komawoyo** [comment]
same result for me, I just disable NAT from VirtualBox to start playing around with redox

**Comment by lehitoskin** [comment]
I've never been able to get networking to do anything. I can either disable networking altogether or just watch as the virtual machine do a whole lot of running in place until I shut it down. It's quite the disappointing experience.

**Comment by jackpot51** [comment]
This is quite odd - I test each release on VirtualBox with the Intel PRO Ethernet. Would @komawoyo and @lehitoskin like to tell me their VirtualBox versions and host OS?

**Comment by komawoyo** [comment]
I believe I found the problem - the default Adapter Type is set to `Intel PRO/1000 MT Desktop (82540EM)` which exhibits the problem above

I have tested the other two available options which boots to the UI completely and virtualbox shows that there is a connection
```Intel PRO/1000 T Server (82543GC)
Intel PRO/1000 MT Server (82545EM)
```

**Comment by lehitoskin** [comment]
Changing the network adapter type to `MT Server` or `T Server` allows it to boot without trickery, but when I try to open the browser it comes up with `error code 19: no such device`

**Comment by komawoyo** [comment]
yup - boot up without being stuck when changing the Adapter Type is most likely because the device is not found by Redox OS during boot up time - which mean the `Intel PRO/1000 MT Desktop (82540EM)` is the main driver we use for internet but that has to be updated (or possibly some issue with virtualbox/windows settings)

**Comment by polymetric1** [comment]
Getting this error too. 
![virtualbox_2017-03-11_13-41-06](https://cloud.githubusercontent.com/assets/13613437/23825903/92c0171e-0660-11e7-8e37-3258243c2156.png)
```
<?xml version="1.0"?>
<!--
** DO NOT EDIT THIS FILE.
** If you make changes to this file while any VirtualBox related application
** is running, your changes will be overwritten later, without taking effect.
** Use VBoxManage or the VirtualBox Manager GUI to make changes.
-->
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.15-windows">
  <Machine uuid="{891e9de5-b4ff-41b4-b76c-60e3b8794892}" name="Redox" OSType="Other_64" snapshotFolder="Snapshots" lastStateChange="2017-03-11T18:41:18Z">
    <MediaRegistry>
      <DVDImages>
        <Image uuid="{3c857c20-0070-4811-b92c-81bb958533d5}" location="G:/Torrent/Downloads/redox-livedisk-0.1.1.iso"/>
        <Image uuid="{e0702cd5-e311-4298-a2bc-126fb1aee3e6}" location="G:/Torrent/redox-livedisk-0.1.1.iso"/>
      </DVDImages>
    </MediaRegistry>
    <ExtraData>
      <ExtraDataItem name="GUI/LastCloseAction" value="PowerOff"/>
      <ExtraDataItem name="GUI/LastNormalWindowPosition" value="0,22,640,480,max"/>
      <ExtraDataItem name="GUI/RestrictedRuntimeDevicesMenuActions" value="HardDrives"/>
      <ExtraDataItem name="GUI/RestrictedRuntimeMachineMenuActions" value="SaveState,PowerOff"/>
      <ExtraDataItem name="GUI/ScaleFactor" value="1"/>
      <ExtraDataItem name="GUI/StatusBar/IndicatorOrder" value="HardDisks,OpticalDisks,FloppyDisks,Network,USB,SharedFolders,Display,VideoCapture,Features,Mouse,Keyboard"/>
    </ExtraData>
    <Hardware>
      <CPU count="4">
        <PAE enabled="true"/>
        <LongMode enabled="true"/>
        <HardwareVirtExLargePages enabled="true"/>
      </CPU>
      <Memory RAMSize="4096"/>
      <Chipset type="ICH9"/>
      <Paravirt provider="KVM"/>
      <Display VRAMSize="128" accelerate3D="true"/>
      <RemoteDisplay enabled="false">
        <VRDEProperties>
          <Property name="TCP/Ports" value="3389"/>
        </VRDEProperties>
      </RemoteDisplay>
      <BIOS>
        <IOAPIC enabled="true"/>
      </BIOS>
      <Network>
        <Adapter slot="0" enabled="true" MACAddress="080027C6C9B3" cable="true" type="82540EM">
          <NAT/>
        </Adapter>
        <Adapter slot="1" cable="true" type="Am79C973"/>
        <Adapter slot="2" cable="true" type="Am79C973"/>
        <Adapter slot="3" cable="true" type="Am79C973"/>
        <Adapter slot="4" cable="true" type="Am79C973"/>
        <Adapter slot="5" cable="true" type="Am79C973"/>
        <Adapter slot="6" cable="true" type="Am79C973"/>
        <Adapter slot="7" cable="true" type="Am79C973"/>
        <Adapter slot="8" type="Am79C973"/>
        <Adapter slot="9" type="Am79C973"/>
        <Adapter slot="10" type="Am79C973"/>
        <Adapter slot="11" type="Am79C973"/>
        <Adapter slot="12" type="Am79C973"/>
        <Adapter slot="13" type="Am79C973"/>
        <Adapter slot="14" type="Am79C973"/>
        <Adapter slot="15" type="Am79C973"/>
        <Adapter slot="16" type="Am79C973"/>
        <Adapter slot="17" type="Am79C973"/>
        <Adapter slot="18" type="Am79C973"/>
        <Adapter slot="19" type="Am79C973"/>
        <Adapter slot="20" type="Am79C973"/>
        <Adapter slot="21" type="Am79C973"/>
        <Adapter slot="22" type="Am79C973"/>
        <Adapter slot="23" type="Am79C973"/>
        <Adapter slot="24" type="Am79C973"/>
        <Adapter slot="25" type="Am79C973"/>
        <Adapter slot="26" type="Am79C973"/>
        <Adapter slot="27" type="Am79C973"/>
        <Adapter slot="28" type="Am79C973"/>
        <Adapter slot="29" type="Am79C973"/>
        <Adapter slot="30" type="Am79C973"/>
        <Adapter slot="31" type="Am79C973"/>
        <Adapter slot="32" type="Am79C973"/>
        <Adapter slot="33" type="Am79C973"/>
        <Adapter slot="34" type="Am79C973"/>
        <Adapter slot="35" type="Am79C973"/>
      </Network>
      <LPT>
        <Port slot="1" enabled="false" IOBase="0x378" IRQ="7"/>
      </LPT>
      <AudioAdapter driver="DirectSound" enabled="true"/>
      <RTC localOrUTC="UTC"/>
      <GuestProperties>
        <GuestProperty name="/VirtualBox/HostInfo/GUI/LanguageID" value="en_US" timestamp="1489257611828028800" flags=""/>
      </GuestProperties>
    </Hardware>
    <StorageControllers>
      <StorageController name="SATA" type="AHCI" PortCount="1" useHostIOCache="false" Bootable="true" IDE0MasterEmulationPort="0" IDE0SlaveEmulationPort="1" IDE1MasterEmulationPort="2" IDE1SlaveEmulationPort="3">
        <AttachedDevice passthrough="false" tempeject="true" type="DVD" hotpluggable="false" port="0" device="0">
          <Image uuid="{e0702cd5-e311-4298-a2bc-126fb1aee3e6}"/>
        </AttachedDevice>
      </StorageController>
    </StorageControllers>
    <Groups>
      <Group name="/Experimental"/>
    </Groups>
  </Machine>
</VirtualBox>
```

**Comment by Dragonrun1** [comment]
Maybe I should open another issue about it instead but just thought I'd add a comment here since it's related. Why is the desktop even being effected by this? In both MS WIndows and Linux if DHCP fails or even if a network driver fails it doesn't prevent my desktop from starting so why does it with Redox? My understanding is part of the reason for moving everything out of the OS was to make things more stable but that doesn't seem to be the case here. I know from personal experience that if the loopback interface gets messed up some how that both X-Windows and to a lesser degree MS Windows breaks but neither care about any of the other interfaces themselves only the applications do. This just seems to be a more fundamental flaw somewhere that what is considered optional since it work fine when no interface is found but then fails only when the interface does exist but there is an issue with it seems to me a bigger problem. Maybe someone can explain that because it really puzzles me and as important as fixing the issue with the network interface not working for everyone is the fact that it's having this wide reaching effect on other things it really shouldn't is much more concerning to me. Let me know if you want me to create another issue or if you think it can be handled here instead.

**Comment by jackpot51** [comment]
I am investigating this. The biggest issue is that this has not been reproducible for me - it appears only on some VirtualBox configurations.

**Comment by Dragonrun1** [comment]
Does make it hard to figure out when you can't reproduce it yourself I understand that. Just to let you know just updated to VirtualBox Version 5.1.18 r114002 (Qt5.6.2) and still have the problem. I have both OpenSuSE(Leap 42.1) and Ubuntu running on the same host without problems and using the same settings for everything on the VM side so I'm pretty sure there isn't any under-laying problem with the VM config itself.

**Comment by jackpot51** [comment]
I think I found the issue - VirtualBox's Programmable Interrupt Controller does not correctly support auto-EOI, and very few OS's use it. I am going back to manual EOI

**Comment by jackpot51** [comment]
I closed all related issues, preferring to track the fixes here. When https://github.com/redox-os/redox/releases/tag/0.1.2 is ready, it should fix this problem.

**Comment by jackpot51** [comment]
The release is now ready - please try it and report!

**Comment by eblot** [comment]
0.1.2 still fails in VmWare (Fusion). I'm not sure #821 is an actual duplicate, at least the original description:

"It can't run in VMware Workstation 12 (Windows 10)
Nothing at all after I choose the interface size"

It does not even make it to DHCP. As soon as the screen size is validated, the CPU halts.
<img width="416" alt="screen shot 2017-03-17 at 21 33 18" src="https://cloud.githubusercontent.com/assets/172423/24061926/b837d61e-0b59-11e7-922f-39bde8096883.png">
<img width="227" alt="screen shot 2017-03-17 at 21 34 40" src="https://cloud.githubusercontent.com/assets/172423/24061930/ba4c8bca-0b59-11e7-94c0-9d604f8aaa83.png">

**Comment by eblot** [comment]
The good news is that QEMU x86_84 is able to boot up 0.1.2:
  `qemu-system-x86_64 -boot d -cdrom livedisk.iso -m 512`
while QEMU i386 dies at the same location than VmWare.

**Comment by jackpot51** [comment]
@eblot is VMWare Fusion x86_64?

**Comment by eblot** [comment]
@jackpot51 Yes, it is. The OS settings for Redox is configured as "Other 64-bit". It boots Linux 64 bits (Debian, Alpine, Ubuntu) and Windows 7 & 10 x64 on the same Mac(s).

**Comment by lehitoskin** [comment]
With PCnet-FAST II and III it boots but when I open the web browser it reports `No such device (os error 19)`.
With `MT Desktop (82540EM)`, `T Server (82543GC)`, and `MT Server (82545EM)` it freezes at the DHCP step.

**Comment by eblot** [comment]
@jackpot51 If it can help, here are the last lines from the VmWare log file, once the screen size is validated in the guest OS:
 
    svga| I125: SVGA enabling SVGA
    svga| I125: SVGA-ScreenMgr: Screen type changed to RegisterMode
    vcpu-0| I125: Vix: [37635 vmxCommands.c:7301]: VMAutomation_HandleCLIHLTEvent. Do nothing.
    vcpu-0| I125: MsgHint: msg.monitorevent.halt
    vcpu-0| I125+ The CPU has been disabled by the guest operating system. Power off or reset the   virtual machine.
    vcpu-0| I125+ ---------------------------------------

Let me know if you want the whole log file.

**Comment by komawoyo** [comment]
I would like to note that I reinstalled VirtualBox to an older version (VB 4.3.40) and Redox OS was able to pass "DHCP 10.0.2.15"
![vb4 3 40](https://cloud.githubusercontent.com/assets/18315233/24063826/4c97c1fa-0b2f-11e7-9db2-71fd910f2153.jpg)

**Comment by komawoyo** [comment]
> With PCnet-FAST II and III it boots but when I open the web browser it reports No such device (os error 19).
@eblot PCnet-FAST is not supported, stick to the Intel drivers - I believe its a problem with the virtual box settings OR some changes to the network stack between the virtual box builds as noted above

**Comment by komawoyo** [comment]
VirtualBox 5.1.12 is the first Version that appears to get stuck at `"Current IP: 10.0.2.15"`
Here's the link to the changelog https://www.virtualbox.org/wiki/Changelog#v12

These are the changes that might be of concern
>E1000: fixed "cable disconnected" issue (Mac OS X guests only; 5.1.10 regression; bug #16260)
>E1000: fixed "TX unit hang" issue (Linux guests only; 5.1.10 regression; bug #16221)

**Comment by jackpot51** [comment]
@komawoyo Thanks for the information - I think that is related. I definitely fixed an issue with IRQ hangs on VirtualBox, but this is yet another issue

**Comment by llde** [comment]
@jackpot51 Paradoxally  I'm unable to boot in the login window  the the 0.1.2 with VB but the 0.1.1 I can.

**Comment by komawoyo** [comment]
whats your setting? I'm able to boot up with 0.1.2 in VB (every version in fact)

**Comment by llde** [comment]
Chipset setting doesn't change anything.  I noticied that on the 0.1.1 the dhcp is failing, in the 0.1.2 block on the current IP 10.2.0.15

Reinstalling VB already done nothing changed

**Comment by komawoyo** [comment]
> Reinstalling VB already done nothing changed
yes refer to the previous comments I've made in this post

**Comment by pythoneer** [comment]
Redox is booting if i am using the PCnet-Fast III network adapter instead of the 8254X which is working with the previous releases.

**Comment by komawoyo** [comment]
@pythoneer, yeah definitely read this thread for some more info

**Comment by llde** [comment]
I was able to boot into virtual box version 0.1.2 and 0.1.3 changing the boot order putting network in the first spot.

**Comment by Dragonrun1** [comment]
Still freezes for me at DHCP with 0.1.3 for me. Just changed out the liveiso image and no other changes.

**Comment by jackpot51** [comment]
I think I can finally duplicate this issue, on Ubuntu with VirtualBox 5.1.14. I can then fix it by enabling network boot and putting it first in the list.

My thought is that the network boot ROM is setting up the PCI configuration or the registers differently and I need to duplicate this behavior in Redox.

**Comment by komawoyo** [comment]
Yes, for some reason Redox is unable to be assigned the correct address from the DHCP. I changed the default network of `10.0.2.0/24` to `10.15.0/24` as shown below and Redox still booted with the same `10.0.2.15` address: I've tested TinyCoreLinux and this issue does not happen to note that the virtualbox settings are valid

![image](https://cloud.githubusercontent.com/assets/18315233/24176444/039e1b46-0e6a-11e7-9c2b-de5d9aa2f146.png)

**Comment by jackpot51** [comment]
Everyone: I am going to post some ISO files for testing. The attached `livedisk.iso` should solve the issue of VirtualBox hanging on the network driver.

**Comment by jackpot51** [comment]
I have created a new ISO I would like to test. This should fix the issue with networking in Virtualbox:
 [livedisk.zip](https://github.com/redox-os/redox/files/860235/livedisk.zip)

The problem was due to the driver not being interrupted during an infinite loop, which was caused by not waiting for the link to be up before sending data.

A change to the kernel can be made to reduce the likelihood of one driver bringing down the system.

**Comment by komawoyo** [comment]
The freeze seems to be fixed. The livedisk was able to boot directly to the UI w/ CD as 1st boot. 
Virtualbox 5.1.18. I have not test whether the internet works or not since my usb mouse, trackpad, and trackpoint (Yoga 12) stopped working since 0.1.3 - it was still working with 0.1.2

Redox was still unable to pick up the new network ip address - not sure if thats the case with anyone else

**Comment by Dragonrun1** [comment]
The livedisk.zip seems to be working for me sitting here at a Starbuck's and even the DHCP seems to not freeze and grabbed an IP :) I'll try it at home as well but looks like you might have solved it or at least the worse of it.

**Comment by komawoyo** [comment]
@Dragonrun1 does the internet works on yours?

**Comment by jackpot51** [comment]
@komawoya please try setting network code back to the default of 10.0.2.0/15

**Comment by komawoyo** [comment]
Virtualbox did not let me use `10.0.2.0/15` in the NAT settings so I used `10.0.2.0/24` (also tried the default "NAT" adapter type

Running `sudo pkg install acid` basically just got stuck, this might be just a windows thing?

![image](https://cloud.githubusercontent.com/assets/18315233/24182282/c2677d6e-0e8e-11e7-801c-c42bbe8bc3aa.png)

**Comment by dagit** [comment]
@jackpot51 I just tried it again on my setup and I can confirm that the new iso works with the Intel network card for me. Thanks!

**Comment by komawoyo** [comment]
@jackpot51 I finally figure it out! It seems that I needed to have the following settings changed to:
`Chipset: PIIX3`
Unchecked `Enable I/O APIC`

By having those two settings set, I was able to regain mouse functionality AND be able to get the internet working!! Awesome stuff.

Just for some thoughts. originally I had `Chipset: ICH9` and Enabled I/O APIC - the mouse worked in version 0.1.2 but not internet. I'm assuming that having having the above settings is a must for internet and mouse to work correctly in Redox

![image](https://cloud.githubusercontent.com/assets/18315233/24217734/d369a256-0f0e-11e7-800d-252ecfa50408.png)

**Comment by polymetric1** [comment]
@komawoyo I tried this, but I get a freeze on the login screen.

**Comment by komawoyo** [comment]
Thats quite odd - its working great on my end - what are the settings you changed from default??

**Comment by Dragonrun1** [comment]
Looks like DHCP works but when I try the included browser stuff is still broken. Here's a couple screenshots of what happens.
![virtualbox_redox_27_03_2017_16_13_01](https://cloud.githubusercontent.com/assets/1431541/24382071/d4eb78b8-1308-11e7-9036-9ad94c740e85.png)
![virtualbox_redox_27_03_2017_16_13_53](https://cloud.githubusercontent.com/assets/1431541/24382070/d4d366a6-1308-11e7-8ab6-3bb928e8d96c.png)

**Comment by jackpot51** [comment]
Let's track further issues somewhere else, if this one is fixed
